export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";
export const UPDATE_PRODUCT_LIST = "UPDATE_PRODUCT_LIST";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const UPDATE_CART_LIST = "UPDATE_CART_LIST";
export const LOADING = "LOADING";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";